name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gcc-multilib
      run:
          sudo apt update && sudo apt install gcc-multilib -y
    - uses: actions/checkout@v3
    - name: make
      run: make
